export const projects = [
  {
    title: 'Crypto Spy',
    year: '2025',
    description: 'crypto tracker chrome extension',
    url: 'https://chromewebstore.google.com/detail/crypto-spy/coimplobgcaanmehcjcholcjclgacnhm',
    sourceCode: 'https://github.com/HarrisonRogers/crypto-spy',
  },
  {
    title: 'Site Whiz',
    year: '2025',
    description: 'AI chat bot to read construction plans',
    url: 'https://site-whiz.vercel.app/',
    sourceCode: 'https://github.com/HarrisonRogers/site-whiz',
  },
  {
    title: 'Kiwi Crypto',
    year: '2024',
    description: 'Track crypto prices in NZD',
    url: '',
    sourceCode: 'https://github.com/HarrisonRogers/Kiwi-Crypto',
  },
  {
    title: 'Jobify',
    year: '2024',
    description: 'Job tracking website',
    url: '',
    sourceCode: 'https://github.com/HarrisonRogers/jobify',
  },
  {
    title: 'Site Pro',
    year: '2024',
    description: 'Building asset management platform',
    url: '',
    sourceCode: 'https://github.com/HarrisonRogers/SitePro',
  },
  {
    title: 'First Table',
    year: '2025',
    description: 'Restaurant booking platform for 50% off meals',
    url: 'https://www.firsttable.co.nz/',
    sourceCode: '',
  },
  {
    title: 'Launch Base Tokens',
    year: '2025',
    description: 'Launch sepolia base crypto tokens',
    url: 'https://launch-base-tokens.vercel.app/',
    sourceCode: 'https://github.com/HarrisonRogers/launch-base-tokens',
  },
  {
    title: 'Eth Blogs',
    year: '2025',
    description: 'Write blogs and set subscription fees with base',
    url: '',
    sourceCode: 'https://github.com/HarrisonRogers/eth-blogs',
  },
];
